name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN for authentication

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/todo:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/todo:${{ github.sha }}
